version: 2

build:
  image: latest

sphinx:
  configuration: docs/conf.py

formats: all

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
    - requirements: docs/requirements2.txt
  system_packages: true